# Generated by Django 5.1.1 on 2024-09-17 23:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_moodentry_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuatPesanan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_pesanan', models.CharField(max_length=255)),
                ('waktu_pemesanan', models.DateField(auto_now_add=True)),
                ('keterangan', models.TextField()),
                ('jumlah_pesanan', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='MoodEntry',
        ),
    ]
